build:
  image: node:12
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - .nuxt/dist

lint:
  image: node:11
  stage: test
  script:
    - npm install
    - npm run lint

test:
  image: node:11
  stage: test
  script:
    - npm install
    - npm run test

production:
  image: ruby:latest
  stage: deploy
  only:
    refs:
        - master
        - schedules
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=work-for-impact-web --api-key=$HEROKU_PRODUCTION_API_KEY
