version: "3"

services:
  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    command: npm run dev
