export default {
  header: 'Cookie Notice',
  whatAreTitle: 'What are cookies?',
  controlTitle: 'How to control cookies',
  controlCookiesTitle: 'How to control cookies',
  useTitle: 'How do we use cookies?',
  whatAreItems: [
    {
      content: [
        {
          text: 'To make this site work properly, we may store cookies (and other technologies, like pixels and beacons) on your device.'
        },
        {
          text: 'A cookie is a small text file that a website saves on your computer or mobile device when you visit the site. It allows the website to remember your actions and preferences (such as login, language, font size, and other display preferences). This way, you don\'t have to keep re-entering them whenever you return to the site.'
        }
      ]
    },
    {
      content: [
        {
          text: 'For more information, please visit AllAboutCookies.org'
        }
      ]
    },
    {
      content: [
        {
          text: 'Cookies can be "First Party," when we run them, or "Third Party" when they are run on your device by a third party when you browse our website. Our website cannot access third-party cookies, nor can other parties access the data in the cookies we use on our website. Cookies are stored for different durations of time on your browser or device.'
        }
      ]
    },
    {
      content: [
        {
          text: 'Session cookies are deleted from your device when you close your web browser.'
        }
      ]
    },
    {
      content: [
        {
          text: 'Persistent cookies will remain on your device until deleted or until they reach their expiry date.'
        }
      ]
    },
    {
      content: [
        {
          text: 'We use tracking pixels to improve or customise our website. Pixels give us the count number of clicks/users/visitors. Our website may contain third party pixel that might let them set or read cookies on your device. This pixel will help us determine the success of our campaigns and website functionalities.'
        }
      ]
    },
    {
      content: [
        {
          text: 'We may use marketing Pixels, such as Facebook and Google AdWords Remarketing Tag, to measure the effectiveness of our ads, to define custom audiences for ad targeting, for dynamic ads campaigns, and to analyse that effectiveness of our website\'s conversion funnels. Please refer to the chart located below where you will find the option to opt-in/out of these technologies.'
        }
      ]
    }
  ],
  controlItems: [
    {
      content: [
        {
          text: 'You can delete all cookies that are already on your device, and you can set most browsers to prevent them from being placed. If you do this, however, some services and functionalities may not work on this website.'
        }
      ]
    },
    {
      content: [
        {
          text: 'Find out how to manage cookies on popular browsers:',
          list: [
            'Google Chrome',
            'Microsoft Edge',
            'Mozilla Firefox',
            'Microsoft Internet Explorer',
            'Opera',
            'Apple Safari'
          ]
        }
      ]
    },
    {
      content: [
        {
          text: 'To find information relating to other browsers, visit the browser developer\'s website.'
        }
      ]
    },
    {
      content: [
        {
          text: 'To opt-out of being tracked by Google Analytics across all websites, visit http://tools.google.com/dlpage/gaoptout.'
        }
      ]
    },
    {
      content: [
        {
          text: 'You can turn off third-party cookies generated by advertisers by going to the Your Online Choices site. You can also visit the trade body representing these advertising platforms for more information: Network Advertising Initiative.'
        }
      ]
    }
  ]
};
